### ISSUE TITLE
Add .env file support

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2-app-basic#108] opened 2017-02-22 07:45 UTC
Moved from https://github.com/yiisoft/yii2/issues/13602

Original text:
I suggest to add .env support, like it's done in Laravel. With it it's much easier to make a basic
config of the app/switching between environments, etc.

**Comment by cebe** [comment] 2017-02-25 22:11
duplicate of #105

**Comment by luislobo** [comment] 2017-03-21 13:00
@cebe #105 is a different issue. That one is about handing environment in basic just like it is done in advanced. This other one is for supporting the use of .env files for setting environment variables, as discussed in https://github.com/yiisoft/yii2/issues/13602

**Comment by schmunk42** [comment] 2017-10-19 13:06
For reference ... We're using this extension for some years now: https://github.com/vlucas/phpdotenv

Usage examples:
- https://github.com/dmstr/docker-yii2-app/blob/master/src/config/env.php
- https://github.com/dmstr/phd5-app/blob/master/src/config/env.php

**Comment by samdark** [comment] 2018-02-17 19:18
Won't be added to 2.0.14. Planned for 2.1.

**Closed by samdark** 2018-02-17 19:18 UTC
Labels: type:enhancement
