### ISSUE TITLE
The file or directory to be published does not exist: vendor\bower\jquery\dist

### ISSUE THREAD

**Issue by albaraam** [yiisoft/yii2-app-basic#143] opened 2017-09-30 09:10 UTC
Can't run the project after installation
Bower packages are installed in vendor/bower-asset folder, while the bower alias (@bower) is pointing to vendor/bower folder
check this pull request #135

**Comment by samdark** [comment] 2017-09-30 10:21
Yes, it duplicate of #135. Will handle it there.

**Closed by samdark** 2017-09-30 10:21 UTC
