### ISSUE TITLE
Missing @webroot alias value in functional tests

### ISSUE THREAD

**Issue by ElisDN** [yiisoft/yii2-app-basic#81] opened 2016-08-09 17:21 UTC
### What steps will reproduce the problem?

Run functional tests:

```
composer exec codecept run functional
```

### What's expected?

```
controllers
models
web
└── assets
    ├── 4e4966d0
    ├── 562e9843
    ├── cfeea075
    └── .gitignore
```

### What do you get instead?

```
@webroot
└── assets
    ├── 4e4966d0
    ├── 562e9843
    └── cfeea075
controllers
models
web
└── assets
    └── .gitignore

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | dev-master
| PHP version      | 5.5.9
| Operating system | Ubuntu

**Comment by samdark** [comment] 2016-08-10 00:07
Duplicate of https://github.com/yiisoft/yii2-app-basic/issues/77

**Closed by samdark** 2016-08-10 00:07 UTC
Labels: bug
